version: '3.8'

services:
  authservice:
    build:
      context: ./Backend/AuthService
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_KEY?Error - JWT_KEY is not set}
      - Jwt__Issuer=${JWT_ISSUER?Error - JWT_ISSUER is not set}
      - Jwt__Audience=${JWT_AUDIENCE?Error - JWT_AUDIENCE is not set}
    networks:
      - myapp-network

  fileservice:
    build:
      context: ./Backend/FileService
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_KEY?Error - JWT_KEY is not set}
      - Jwt__Issuer=${JWT_ISSUER?Error - JWT_ISSUER is not set}
      - Jwt__Audience=${JWT_AUDIENCE?Error - JWT_AUDIENCE is not set}
      - FrontendUrl=${FRONTEND_URL?Error - FRONTEND_URL is not set}
    volumes:
      - fileservice-uploads:/app/uploads
    networks:
      - myapp-network
    depends_on:
      - authservice

  searchservice:
    build:
      context: ./Backend/SearchService
      dockerfile: Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - LuceneIndexPath=/app/lucene_index
    volumes:
      - searchservice-index:/app/lucene_index
    networks:
      - myapp-network
    depends_on:
      - fileservice

  backendgateway:
    build:
      context: ./Backend/BackendGateway
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - myapp-network
    depends_on:
      - authservice
      - fileservice
      - searchservice

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - API_BASE_URL=http://backendgateway
    networks:
      - myapp-network
    depends_on:
      - backendgateway

volumes:
  fileservice-uploads:
  searchservice-index:

networks:
  myapp-network:
    driver: bridge
