version: '3.8'

services:
  authservice:
    build:
      context: ./Backend/AuthService
      dockerfile: Dockerfile
    image: mifimov345/authservice:latest
    ports:
      - "5000:80"

  backendgateway:
    build:
      context: ./Backend/BackendGateway
      dockerfile: Dockerfile
    image: mifimov345/backendgateway:latest
    ports:
      - "5001:80"

  fileservice:
    build:
      context: ./Backend/FileService
      dockerfile: Dockerfile
    image: mifimov345/fileservice:latest
    ports:
      - "5002:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: mifimov345/frontend:latest
    ports:
      - "8080:80"
