version: '3.8'

services:
  authservice:
    build:
      context: ./Backend/AuthService
    image: mydockerhubuser/authservice:latest
    ports:
      - "5000:80"
  
  backendgateway:
    build:
      context: ./Backend/BackendGateway
    image: mydockerhubuser/backendgateway:latest
    ports:
      - "5001:80"

  fileservice:
    build:
      context: ./Backend/FileService
    image: mydockerhubuser/fileservice:latest
    ports:
      - "5002:80"

  frontend:
    build:
      context: ./frontend
    image: mydockerhubuser/frontend:latest
    ports:
      - "8080:80"
