name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Клонирует репозиторий

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push AuthService Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Убедитесь, что контекст - это корень репозитория
        file: Backend/AuthService/Dockerfile  # Путь к Dockerfile для AuthService
        push: true
        tags: mydockerhubuser/authservice:latest

    - name: Build and push BackendGateway Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Контекст сборки для BackendGateway
        file: Backend/BackendGateway/Dockerfile
        push: true
        tags: mydockerhubuser/backendgateway:latest

    - name: Build and push FileService Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Контекст сборки для FileService
        file: Backend/FileService/Dockerfile
        push: true
        tags: mydockerhubuser/fileservice:latest

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Контекст сборки для Frontend
        file: frontend/Dockerfile
        push: true
        tags: mydockerhubuser/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Deploy Docker Containers using docker-compose
      run: |
        docker-compose -f docker-compose.yml up -d  # Запускаем все контейнеры
