name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Работает на основной ветке
  pull_request:
    branches:
      - main  # Работает при pull request

jobs:
  build:
    runs-on: ubuntu-latest  # Запуск на Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Клонирует ваш репозиторий

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./AuthService/Dockerfile
        push: true
        tags: mydockerhubuser/authservice:latest

    - name: Build and push BackendGateway Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./BackendGateway/Dockerfile
        push: true
        tags: mydockerhubuser/backendgateway:latest

    - name: Build and push FileService Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./FileService/Dockerfile
        push: true
        tags: mydockerhubuser/fileservice:latest

    - name: Build and push FrontendVue Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./FrontendVue/Dockerfile
        push: true
        tags: mydockerhubuser/frontendvue:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Run integration tests
      run: |
        docker-compose -f docker-compose.yml up -d  # Запускаем контейнеры
        dotnet test ./AuthService.Tests/AuthService.Tests.csproj  # Запускаем тесты для AuthService
        dotnet test ./BackendGateway.Tests/BackendGateway.Tests.csproj  # Тесты для BackendGateway
        dotnet test ./FileService.Tests/FileService.Tests.csproj  # Тесты для FileService
        docker-compose down  # Останавливаем контейнеры после тестов
